[platformio]
src_dir = main

[env:esp32cam-jade]
platform = espressif32@6.12.0
board = esp32cam
framework = espidf
board_build.sdkconfig = sdkconfig.esp32cam-jade

; Extra script to generate embedded .S files
; (pinserver public key and logo binaries)
extra_scripts = tools/pio_gen_embeds.py

; Use Jade custom partition table
board_build.partitions = partitions.csv

; Build flags:
; - Enable C++ exceptions
; - Select rpi_lcd display driver
build_flags =
  -fexceptions
  -DCONFIG_RPI_LCD_DISPLAY=1
  -IC:/Users/alyss/.platformio/packages/framework-espidf/components/esp_driver_gpio/include
  -IC:/Users/alyss/.platformio/packages/framework-espidf/components/esp_driver_spi/include
  -IC:/ESP-Projects/Jade/components/libsodium/libsodium/src/libsodium/include

monitor_speed = 115200
